spring:
  datasource:
    url: jdbc:mysql://localhost:3306/player_info?useSSL=false
    username: root
    password: kahng
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 1111
